// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.mulberry.athena.remote.rmi;

public final class RmiInvocationWrapper_Stub
    extends java.rmi.server.RemoteStub
    implements com.mulberry.athena.remote.rmi.RmiInvocationHandler
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getInterfaces_0;
    private static java.lang.reflect.Method $method_invoke_1;
    
    static {
	try {
	    $method_getInterfaces_0 = com.mulberry.athena.remote.ServiceInterfacesAware.class.getMethod("getInterfaces", new java.lang.Class[] {});
	    $method_invoke_1 = com.mulberry.athena.remote.RemoteInvocationHandler.class.getMethod("invoke", new java.lang.Class[] {com.mulberry.athena.remote.RemoteInvocation.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RmiInvocationWrapper_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getInterfaces()
    public java.util.Set getInterfaces()
	throws java.lang.Exception
    {
	Object $result = ref.invoke(this, $method_getInterfaces_0, null, -8574265364247758665L);
	return ((java.util.Set) $result);
    }
    
    // implementation of invoke(RemoteInvocation)
    public com.mulberry.athena.remote.RemoteInvocationResult invoke(com.mulberry.athena.remote.RemoteInvocation $param_RemoteInvocation_1)
	throws java.lang.Exception
    {
	Object $result = ref.invoke(this, $method_invoke_1, new java.lang.Object[] {$param_RemoteInvocation_1}, -1167934894633003505L);
	return ((com.mulberry.athena.remote.RemoteInvocationResult) $result);
    }
}
