
package com.apple.jaxws.sample2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://jaxws.remote.apple.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://jaxws.remote.apple.com/", className = "com.apple.jaxws.sample.Greet")
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://jaxws.remote.apple.com/", className = "com.apple.jaxws.sample.GreetResponse")
    public String greet(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.apple.jaxws.sample.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://jaxws.remote.apple.com/", className = "com.apple.jaxws.sample.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://jaxws.remote.apple.com/", className = "com.apple.jaxws.sample.GetUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
